;;; vortel-lsp-actions-rename-tests.el --- Code action and rename tests for vortel-lsp -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;; Author: vortel-lsp contributors

;;; Code:

(require 'cl-lib)
(require 'ert)

(require 'vortel-lsp-test-helpers)

(ert-deftest vortel-lsp-test-resolve-code-action-supported-path ()
  (let* ((client (vortel-lsp-test-make-client))
         (item (vortel-lsp-make-hash "title" "Fix all"))
         (resolved (vortel-lsp-make-hash "title" "Fix all" "edit" (vortel-lsp-make-hash))))
    (cl-letf (((symbol-function 'vortel-lsp-client-code-action-resolve-supported-p)
               (lambda (_client) t))
              ((symbol-function 'vortel-lsp--request-sync)
               (lambda (_client method params _timeout)
                 (should (string= method "codeAction/resolve"))
                 (should (eq params item))
                 (list :ok t :result resolved))))
      (should (eq (vortel-lsp--resolve-code-action client item) resolved)))))

(ert-deftest vortel-lsp-test-resolve-code-action-unsupported-path ()
  (let* ((client (vortel-lsp-test-make-client))
         (item (vortel-lsp-make-hash "title" "Fix all"))
         (called nil))
    (cl-letf (((symbol-function 'vortel-lsp-client-code-action-resolve-supported-p)
               (lambda (_client) nil))
              ((symbol-function 'vortel-lsp--request-sync)
               (lambda (&rest _args)
                 (setq called t)
                 (list :ok nil))))
      (should (eq (vortel-lsp--resolve-code-action client item) item))
      (should-not called))))

(ert-deftest vortel-lsp-test-execute-code-action-record-disabled ()
  (let* ((client (vortel-lsp-test-make-client))
         (resolved (vortel-lsp-make-hash
                    "title" "Disabled action"
                    "disabled" (vortel-lsp-make-hash "reason" "not available")))
         (action (list :client client :item resolved))
         (result nil))
    (cl-letf (((symbol-function 'vortel-lsp--resolve-code-action)
               (lambda (_client _item) resolved)))
      (setq result (vortel-lsp--execute-code-action-record action)))
    (should-not (plist-get result :ok))
    (should (equal (plist-get result :reason) "not available"))))

(ert-deftest vortel-lsp-test-execute-code-action-record-applies-edit-and-command ()
  (let* ((client (vortel-lsp-test-make-client))
         (command (vortel-lsp-make-hash "command" "workspace.fix"))
         (resolved (vortel-lsp-make-hash "title" "Fix"
                                         "edit" (vortel-lsp-make-hash)
                                         "command" command))
         (action (list :client client :item (vortel-lsp-make-hash "title" "Fix")))
         (calls nil)
         (result nil))
    (cl-letf (((symbol-function 'vortel-lsp--resolve-code-action)
               (lambda (_client _item) resolved))
              ((symbol-function 'vortel-lsp--apply-workspace-edit-result)
               (lambda (_client _edit)
                 (setq calls (append calls '(edit)))
                 (list :ok t)))
              ((symbol-function 'vortel-lsp--execute-command-object)
               (lambda (_client in-command)
                 (should (eq in-command command))
                 (setq calls (append calls '(command)))
                 (list :ok t))))
      (setq result (vortel-lsp--execute-code-action-record action)))
    (should (plist-get result :ok))
    (should (equal calls '(edit command)))))

(ert-deftest vortel-lsp-test-execute-code-action-record-fails-without-edit-or-command ()
  (let* ((client (vortel-lsp-test-make-client))
         (resolved (vortel-lsp-make-hash "title" "No-op action"))
         (action (list :client client :item resolved))
         (result nil))
    (cl-letf (((symbol-function 'vortel-lsp--resolve-code-action)
               (lambda (_client _item) resolved)))
      (setq result (vortel-lsp--execute-code-action-record action)))
    (should-not (plist-get result :ok))
    (should (equal (plist-get result :reason) "code action has no edit or command"))))

(ert-deftest vortel-lsp-test-code-actions-errors-when-empty ()
  (cl-letf (((symbol-function 'vortel-lsp--collect-code-actions)
             (lambda () nil)))
    (should-error (vortel-lsp-code-actions) :type 'user-error)))

(ert-deftest vortel-lsp-test-code-actions-shows-success-message ()
  (let* ((action (list :title "Fix typo" :item (vortel-lsp-make-hash) :client nil))
         (message-text nil))
    (cl-letf (((symbol-function 'vortel-lsp--collect-code-actions)
               (lambda () (list action)))
              ((symbol-function 'vortel-lsp--read-code-action)
               (lambda (_actions) action))
              ((symbol-function 'vortel-lsp--execute-code-action-record)
               (lambda (_action) (list :ok t)))
              ((symbol-function 'message)
               (lambda (fmt &rest args)
                 (setq message-text (apply #'format fmt args)))))
      (vortel-lsp-code-actions))
    (should (equal message-text "code action applied: Fix typo"))))

(ert-deftest vortel-lsp-test-code-actions-surfaces-failure-reason ()
  (let ((action (list :title "Fix typo" :item (vortel-lsp-make-hash) :client nil)))
    (cl-letf (((symbol-function 'vortel-lsp--collect-code-actions)
               (lambda () (list action)))
              ((symbol-function 'vortel-lsp--read-code-action)
               (lambda (_actions) action))
              ((symbol-function 'vortel-lsp--execute-code-action-record)
               (lambda (_action)
                 (list :ok nil :reason "cannot apply"))))
      (should-error (vortel-lsp-code-actions)
                    :type 'user-error))))

(ert-deftest vortel-lsp-test-rename-symbol-rejects-empty-target ()
  (should-error (vortel-lsp-rename-symbol "") :type 'user-error))

(ert-deftest vortel-lsp-test-rename-symbol-errors-without-attachments ()
  (vortel-lsp-test-with-temp-file-buffer "main.c" "int main(void) { return 0; }\n"
    (goto-char (point-min))
    (cl-letf (((symbol-function 'vortel-lsp--attachments-for-feature)
               (lambda (_feature) nil)))
      (should-error (vortel-lsp-rename-symbol "renamed") :type 'user-error))))

(ert-deftest vortel-lsp-test-rename-symbol-falls-back-to-later-client ()
  (vortel-lsp-test-with-temp-file-buffer "main.c" "int value = 1;\n"
    (goto-char (point-min))
    (search-forward "value")
    (let* ((client-a (vortel-lsp-test-make-client :id 1 :name "a"))
           (client-b (vortel-lsp-test-make-client :id 2 :name "b"))
           (workspace-edit (vortel-lsp-make-hash "changes" (make-hash-table :test #'equal)))
           (apply-client nil)
           (message-text nil))
      (cl-letf (((symbol-function 'vortel-lsp--attachments-for-feature)
                 (lambda (_feature)
                   (list (list :client client-a)
                         (list :client client-b))))
                ((symbol-function 'vortel-lsp--request-sync)
                 (lambda (client method _params _timeout)
                   (should (string= method "textDocument/rename"))
                   (if (eq client client-a)
                       (list :ok nil :error (vortel-lsp-make-hash "message" "rename rejected"))
                     (list :ok t :result workspace-edit))))
                ((symbol-function 'vortel-lsp--apply-workspace-edit-result)
                 (lambda (client _workspace-edit)
                   (setq apply-client client)
                   (list :ok t)))
                ((symbol-function 'message)
                 (lambda (fmt &rest args)
                   (setq message-text (apply #'format fmt args)))))
        (vortel-lsp-rename-symbol "renamed")
        (should (eq apply-client client-b))
        (should (equal message-text "renamed to renamed"))))))

(ert-deftest vortel-lsp-test-rename-symbol-surfaces-apply-failure ()
  (vortel-lsp-test-with-temp-file-buffer "main.c" "int value = 1;\n"
    (goto-char (point-min))
    (search-forward "value")
    (let* ((client (vortel-lsp-test-make-client))
           (workspace-edit (vortel-lsp-make-hash "changes" (make-hash-table :test #'equal))))
      (cl-letf (((symbol-function 'vortel-lsp--attachments-for-feature)
                 (lambda (_feature) (list (list :client client))))
                ((symbol-function 'vortel-lsp--request-sync)
                 (lambda (_client method _params _timeout)
                   (should (string= method "textDocument/rename"))
                   (list :ok t :result workspace-edit)))
                ((symbol-function 'vortel-lsp--apply-workspace-edit-result)
                 (lambda (_client _workspace-edit)
                   (list :ok nil :reason "workspace edit rejected"))))
        (should-error (vortel-lsp-rename-symbol "renamed")
                      :type 'user-error)))))

(provide 'vortel-lsp-actions-rename-tests)

;;; vortel-lsp-actions-rename-tests.el ends here
